resolver: lts-18.27
packages:
- .

# Note: This section will be ignored by stack, on non-NixOS systems.
# It can be explicitly enabled on non-NixOS systems by passing --nix.
# On NixOS this section is needed to bring the non-Haskell dependencies
# into scope.
nix:
  packages:
    - zlib
